/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author hoang
 */

import java.sql.*;
import models.ConnectDB;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class Customer extends javax.swing.JPanel {

    /**
     * Creates new form Account
     */
    public Customer() {
        initComponents();
        CustomerTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCid = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtCname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtCphone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txtCaddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnClear1 = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1114, 587));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel7.setText("Customer");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 116, 135));
        jLabel8.setText("Customer Infomation");

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel9.setText("Customer ID");

        txtCid.setFont(new java.awt.Font("Bell MT", 0, 13)); // NOI18N
        txtCid.setText("Enter ID");
        txtCid.setBorder(null);
        txtCid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCidFocusLost(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(255, 71, 127));
        jSeparator7.setForeground(new java.awt.Color(255, 116, 135));

        jSeparator8.setBackground(new java.awt.Color(255, 71, 127));
        jSeparator8.setForeground(new java.awt.Color(255, 116, 135));

        txtCname.setFont(new java.awt.Font("Bell MT", 0, 13)); // NOI18N
        txtCname.setText("Enter Name");
        txtCname.setBorder(null);
        txtCname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCnameFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel10.setText("Customer Name");

        jSeparator9.setBackground(new java.awt.Color(255, 71, 127));
        jSeparator9.setForeground(new java.awt.Color(255, 116, 135));

        txtCphone.setFont(new java.awt.Font("Bell MT", 0, 13)); // NOI18N
        txtCphone.setText("Enter Contact");
        txtCphone.setBorder(null);
        txtCphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCphoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCphoneFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel11.setText("Customer Contact");

        jSeparator10.setBackground(new java.awt.Color(255, 71, 127));
        jSeparator10.setForeground(new java.awt.Color(255, 116, 135));

        txtCaddress.setFont(new java.awt.Font("Bell MT", 0, 13)); // NOI18N
        txtCaddress.setText("Enter Address");
        txtCaddress.setBorder(null);
        txtCaddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCaddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCaddressFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel12.setText("Customer Address");

        btnClear1.setBackground(new java.awt.Color(255, 255, 255));
        btnClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/available_updates_24px.png"))); // NOI18N
        btnClear1.setToolTipText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        btnAdd1.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_new_24px.png"))); // NOI18N
        btnAdd1.setToolTipText("Add");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnUpdate1.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update_24px.png"))); // NOI18N
        btnUpdate1.setToolTipText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnDelete1.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/erase_24px.png"))); // NOI18N
        btnDelete1.setToolTipText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCid)
                    .addComponent(jSeparator7)
                    .addComponent(txtCname)
                    .addComponent(jSeparator8)
                    .addComponent(txtCphone)
                    .addComponent(jSeparator9)
                    .addComponent(txtCaddress)
                    .addComponent(jSeparator10)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAdd1)
                        .addGap(87, 87, 87)
                        .addComponent(btnUpdate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete1)
                        .addGap(107, 107, 107)
                        .addComponent(btnClear1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCphone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClear1)
                        .addComponent(btnAdd1)
                        .addComponent(btnUpdate1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCustomer.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Contact", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomer.setGridColor(new java.awt.Color(255, 255, 255));
        tblCustomer.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblCustomer.setRowHeight(25);
        tblCustomer.setSelectionBackground(new java.awt.Color(255, 116, 135));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        btnPrint.setBackground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print_24px.png"))); // NOI18N
        btnPrint.setToolTipText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrint, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrint)
                        .addGap(0, 18, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void CustomerTable() {
        try {
            Connection conn = new ConnectDB().getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from customers");
            
            tblCustomer.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void txtCidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidFocusGained
        // TODO add your handling code here:
        if (txtCid.getText().equals("Enter ID")) {
            txtCid.setText("");
        }
    }//GEN-LAST:event_txtCidFocusGained

    private void txtCidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidFocusLost
        // TODO add your handling code here:
        if (txtCid.getText().equals("")) {
            txtCid.setText("Enter ID");
        }
    }//GEN-LAST:event_txtCidFocusLost

    private void txtCnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnameFocusGained
        // TODO add your handling code here:
        if (txtCname.getText().equals("Enter Name")) {
            txtCname.setText("");
        }
    }//GEN-LAST:event_txtCnameFocusGained

    private void txtCnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnameFocusLost
        // TODO add your handling code here:
        if (txtCname.getText().equals("")) {
            txtCname.setText("Enter Name");
        }
    }//GEN-LAST:event_txtCnameFocusLost

    private void txtCphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCphoneFocusGained
        // TODO add your handling code here:
        if (txtCphone.getText().equals("Enter Contact")) {
            txtCphone.setText("");
        }
    }//GEN-LAST:event_txtCphoneFocusGained

    private void txtCphoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCphoneFocusLost
        // TODO add your handling code here:
        if (txtCphone.getText().equals("")) {
            txtCphone.setText("Enter Contact");
        }
    }//GEN-LAST:event_txtCphoneFocusLost

    private void txtCaddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCaddressFocusGained
        // TODO add your handling code here:
        if (txtCaddress.getText().equals("Enter Address")) {
            txtCaddress.setText("");
        }
    }//GEN-LAST:event_txtCaddressFocusGained

    private void txtCaddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCaddressFocusLost
        // TODO add your handling code here:
        if (txtCaddress.getText().equals("")) {
            txtCaddress.setText("Enter Address");
        }
    }//GEN-LAST:event_txtCaddressFocusLost

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
        txtCid.setText("Enter ID");
        txtCname.setText("Enter Name");
        txtCphone.setText("Enter Contact");
        txtCaddress.setText("Enter Address");
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        String id = txtCid.getText().trim();
        String name = txtCname.getText().trim();
        String phone = txtCphone.getText().trim();
        String address = txtCaddress.getText().trim();

        if (id.equals("Enter ID") || name.equals("Enter Name")) {
            JOptionPane.showMessageDialog(null, "Please Enter Customer ID and Name");
        } else {
            try {
                Connection conn = new ConnectDB().getConnection();
                PreparedStatement st = null;

                String sql = "insert into customers(customer_id, customer_name, phone, customer_address)"
                + "value(?, ?, ?, ?)";
                st = conn.prepareStatement(sql);

                st.setString(1, id);
                st.setString(2, name);
                st.setString(3, phone);
                st.setString(4, address);

                st.execute();

                CustomerTable();

                JOptionPane.showMessageDialog(null, "Successfully");

                txtCid.setText("Enter ID");
                txtCname.setText("Enter Name");
                txtCphone.setText("Enter Contact");
                txtCaddress.setText("Enter Address");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ID is already Exist");
            }
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        String id = txtCid.getText().trim();
        String name = txtCname.getText().trim();
        String phone = txtCphone.getText().trim();
        String address = txtCaddress.getText().trim();

        try {
            Connection conn = new ConnectDB().getConnection();

            int row = tblCustomer.getSelectedRow();
            String value = (tblCustomer.getModel()).getValueAt(row, 0).toString();

            String sql = "update customers set customer_id = ?, customer_name = ?, "
            + "phone = ?, customer_address = ? where customer_id = ?";
            PreparedStatement st = conn.prepareStatement(sql);

            st.setString(1, id);
            st.setString(2, name);
            st.setString(3, phone);
            st.setString(4, address);
            st.setString(5, value);
            st.executeUpdate();

            CustomerTable();

            JOptionPane.showMessageDialog(null, "Successfully Updated");

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        if (txtCid.getText().equals("Enter ID")) {
            JOptionPane.showMessageDialog(null, "Enter The Customer To be Deleted");
        } else {
            try {
                Connection conn = new ConnectDB().getConnection();

                int row = tblCustomer.getSelectedRow();
                String value = (tblCustomer.getModel()).getValueAt(row, 0).toString();

                String sql = "delete from customers where customer_id = ?";
                PreparedStatement st = conn.prepareStatement(sql);

                st.setString(1, value);
                st.executeUpdate();

                CustomerTable();

                txtCid.setText("Enter ID");
                txtCname.setText("Enter Name");
                txtCphone.setText("Enter Contact");
                txtCaddress.setText("Enter Address");

                JOptionPane.showMessageDialog(null, "Successfully Delete");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tblCustomer.getModel();

        String tblId = tableModel.getValueAt(tblCustomer.getSelectedRow(), 0).toString();
        String tblName = tableModel.getValueAt(tblCustomer.getSelectedRow(), 1).toString();
        String tblPhone = tableModel.getValueAt(tblCustomer.getSelectedRow(), 2).toString();
        String tblAddress = tableModel.getValueAt(tblCustomer.getSelectedRow(), 3).toString();

        txtCid.setText(tblId);
        txtCname.setText(tblName);
        txtCphone.setText(tblPhone);
        txtCaddress.setText(tblAddress);
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            tblCustomer.print(JTable.PrintMode.NORMAL);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtCaddress;
    private javax.swing.JTextField txtCid;
    private javax.swing.JTextField txtCname;
    private javax.swing.JTextField txtCphone;
    // End of variables declaration//GEN-END:variables
}
