/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.UserAccountDAO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import models.UserAccount;

/**
 *
 * @author HP
 */
public class Information extends javax.swing.JPanel {

    /**
     * Creates new form Infromation
     */
    int currentRowIndex = -1;
    boolean isAdd = false;

    public Information() {
        initComponents();
        new UserAccountDAO().getTableModel(jTable1, "select * from useraccount");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblFullname1 = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        lblBirthday1 = new javax.swing.JLabel();
        lblPosition1 = new javax.swing.JLabel();
        lblGender1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtFullname = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        dDate = new com.toedter.calendar.JDateChooser();
        rbMAle = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        rbAdmin = new javax.swing.JRadioButton();
        rbEmp = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(1114, 587));

        jPanel1.setBackground(java.awt.Color.pink);

        jLabel2.setBackground(java.awt.Color.pink);
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ACOUNT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(22);
        jTable1.setSelectionBackground(java.awt.Color.pink);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Who are you looking up? Search by Name or ID: ");

        txtSearch.setBackground(new java.awt.Color(51, 255, 204));
        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setText("Add new");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refesh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnDelete)
                        .addGap(44, 44, 44)
                        .addComponent(btnRefresh)
                        .addGap(62, 62, 62)
                        .addComponent(btnAdd)
                        .addGap(46, 46, 46)
                        .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd)
                    .addComponent(btnRefresh)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Infomation");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 255)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ID:");

        lblFullname1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblFullname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFullname1.setText("Fullname:");

        lblUsername1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblUsername1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername1.setText("Username:");

        lblPassword1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPassword1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword1.setText("Password:");

        lblAddress1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAddress1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress1.setText("Address:");

        lblPhone1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPhone1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhone1.setText("Phone:");

        lblBirthday1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBirthday1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBirthday1.setText("Birthday:");

        lblPosition1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPosition1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosition1.setText("Position:");

        lblGender1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblGender1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGender1.setText("Gender:");

        txtUsername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtFullname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtFullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPhone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonGroup1.add(rbMAle);
        rbMAle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbMAle.setText("Male");

        buttonGroup1.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbFemale.setText("Female");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-icon.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbAdmin);
        rbAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbAdmin.setText("Admin");

        buttonGroup2.add(rbEmp);
        rbEmp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbEmp.setText("Employee");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(lblAddress1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPhone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBirthday1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGender1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPosition1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAddress)
                                    .addComponent(txtPassword)
                                    .addComponent(txtPhone)
                                    .addComponent(dDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbMAle)
                                            .addComponent(rbAdmin))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbEmp)
                                            .addComponent(rbFemale)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFullname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername)
                                    .addComponent(txtFullname)
                                    .addComponent(txtID))))
                        .addGap(69, 69, 69)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 148, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullname1)
                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword1)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress1)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone1)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBirthday1)
                    .addComponent(dDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFemale)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGender1)
                        .addComponent(rbMAle)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPosition1)
                        .addComponent(rbAdmin))
                    .addComponent(rbEmp))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

    }//GEN-LAST:event_jTable1KeyReleased

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        isAdd = false;
        currentRowIndex = jTable1.getSelectedRow();
        if (currentRowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please choose row to change", "Message", JOptionPane.YES_NO_OPTION);
            return;
        } else {
            UserAccount u = new UserAccount(
                    (String) jTable1.getValueAt(currentRowIndex, 0),
                    (String) jTable1.getValueAt(currentRowIndex, 1),
                    (String) jTable1.getValueAt(currentRowIndex, 2),
                    (String) jTable1.getValueAt(currentRowIndex, 3),
                    (String) jTable1.getValueAt(currentRowIndex, 4),
                    (String) jTable1.getValueAt(currentRowIndex, 5),
                    (Date) jTable1.getValueAt(currentRowIndex, 6),
                    (String) jTable1.getValueAt(currentRowIndex, 7),
                    jTable1.getValueAt(currentRowIndex, 8).equals("Admin") ? 1 : 0
            );
            txtID.setText(u.getUser_id());
            txtFullname.setText(u.getFullname());
            txtUsername.setText(u.getUsername());
            txtPassword.setText(u.getPassword());
            txtAddress.setText(u.getAddress());
            txtPhone.setText(u.getPhone_number());
            if (u.getIs_admin() == 1) {
                rbAdmin.setSelected(true);
            } else {
                rbEmp.setSelected(true);
            }

            if (u.getGender().equals("Male")) {
                rbMAle.setSelected(true);
            } else {
                rbFemale.setSelected(true);
            }
            dDate.setDate(u.getBirthdate());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        isAdd = true;
        txtID.setText("");
        txtID.setEditable(true);
        txtPassword.setText("");
        txtFullname.setText("");
        txtUsername.setText("");
        txtAddress.setText("");
        txtPhone.setText("");
        dDate.setDate(null);
        rbMAle.setSelected(true);
        rbAdmin.setSelected(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String id = txtID.getText().trim();
        String fullname = txtFullname.getText().trim();
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();
        String address = txtAddress.getText().trim();
        String phone = txtPhone.getText().trim();
        String date = dDate.getDate() == null ? "" : new SimpleDateFormat("yyyy-MM-dd").format(dDate.getDate());
        String gender = rbMAle.isSelected() ? "Male" : "Female";
        int isAdmin = rbAdmin.isSelected() ? 1 : 0;
        if (id.equals("")) {
            JOptionPane.showMessageDialog(this, "ID is empty");
            return;
        }
        if (fullname.equals("")) {
            JOptionPane.showMessageDialog(this, "Fullname is empty");
            return;
        }
        if (username.equals("")) {
            JOptionPane.showMessageDialog(this, "Username is empty");
            return;
        }
        if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Password is empty");
            return;
        }
        if (address.equals("")) {
            JOptionPane.showMessageDialog(this, "Address is empty");
            return;
        }
        if (phone.equals("")) {
            JOptionPane.showMessageDialog(this, "Phone is empty");
            return;
        }
        if (date.equals("")) {
            JOptionPane.showMessageDialog(this, "Please input birthday");
            return;
        }
        java.sql.Connection connection = new models.ConnectDB().getConnection();
        if (isAdd) {
            String sql = "insert into useraccount value(?,?,?,?,?,?,?,?,?)";
            try {
                java.sql.Statement st = connection.createStatement();
                java.sql.ResultSet rs = st.executeQuery("select * from useraccount");
                while (rs.next()) {
                    if (rs.getString("user_id").equals(id)) {
                        JOptionPane.showMessageDialog(this, "User ID is exist");
                        return;
                    }
                    if (rs.getString("username").equals(username)) {
                        JOptionPane.showMessageDialog(this, "Username is exist");
                        return;
                    }
                }
                java.sql.PreparedStatement pst = connection.prepareStatement(sql);
                pst.setString(1, id);
                pst.setString(2, fullname);
                pst.setString(3, username);
                pst.setString(4, password);
                pst.setString(5, address);
                pst.setString(6, phone);
                pst.setString(7, date);
                pst.setString(8, gender);
                pst.setInt(9, isAdmin);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Add new user success !!! ");
                new UserAccountDAO().getTableModel(jTable1, "select * from useraccount");
                return;
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Please check your input");
                return;
            }
        } else {
            String sql = "UPDATE useraccount SET fullname = ?,username = ?,address = ?,phone_number = ?,birthday=?,gender=?,is_admin=? WHERE user_id = ?";
            try {
                java.sql.PreparedStatement pst = connection.prepareStatement(sql);
                pst.setString(1, fullname);
                pst.setString(2, username);
                pst.setString(3, address);
                pst.setString(4, phone);
                pst.setString(5, date);
                pst.setString(6, gender);
                pst.setInt(7, isAdmin);
                pst.setString(8, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Update success");
            } catch (java.sql.SQLException e) {
                JOptionPane.showMessageDialog(this, "Error line 581: " + e);
                return;
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        new UserAccountDAO().getTableModel(jTable1, "select * from useraccount where user_id like '%" + txtSearch.getText().trim() + "%' or fullname like '%" + txtSearch.getText().trim() + "%'");

    }//GEN-LAST:event_txtSearchCaretUpdate

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        new UserAccountDAO().getTableModel(jTable1, "select * from useraccount");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        currentRowIndex = jTable1.getSelectedRow();
        if (currentRowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please choose row to delete !!!", "Message", JOptionPane.YES_NO_OPTION);
            return;
        } else {
            int result = JOptionPane.showConfirmDialog(this, "Delete ??", "Message", JOptionPane.YES_NO_CANCEL_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                String id = (String) jTable1.getValueAt(currentRowIndex, 0);
                new UserAccountDAO().delete("useraccount", "user_id", id);
                new UserAccountDAO().getTableModel(jTable1, "select * from useraccount");
            }else{
                
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser dDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblBirthday1;
    private javax.swing.JLabel lblFullname1;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPosition1;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbEmp;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMAle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
