/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.sql.*;
import models.ConnectDB;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.Random;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.UserAccount;

public final class Order extends javax.swing.JPanel {

    public int ftotal = 0;

    public Order(UserAccount userLogin) {
        initComponents();

        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();

        lblDate.setText(dFormat.format(date));

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("hh:mm:ss");
        LocalDateTime now = LocalDateTime.now();

        lblTime.setText(dtf.format(now));

        getUserid(userLogin);

        uid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCusPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCusAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProdId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtProdPrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtProdQty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtPaid = new javax.swing.JTextField();
        txtReturn = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        txtCusId = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        uid = new javax.swing.JTextField();
        btnCusReset = new javax.swing.JButton();
        btnAddCus = new javax.swing.JButton();
        btnAddProd = new javax.swing.JButton();
        btnProdReset = new javax.swing.JButton();
        btnSave2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();

        btnSave1.setBackground(new java.awt.Color(255, 255, 255));
        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_new_24px.png"))); // NOI18N
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1114, 587));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billing_machine_100px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel2.setText("Order");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setText("jLabel3");

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Time:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer:");

        txtCusName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Phone");

        txtCusPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCusPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusPhoneActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Address");

        txtCusAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Product:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("ID");

        txtProdId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdIdActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Name");

        txtProdName.setEditable(false);
        txtProdName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Price");

        txtProdPrice.setEditable(false);
        txtProdPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProdPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdPriceActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Qty");

        txtProdQty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProdQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdQtyActionPerformed(evt);
            }
        });

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price", "Quantity", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrder.setRowHeight(25);
        tblOrder.setSelectionBackground(new java.awt.Color(255, 116, 135));
        jScrollPane1.setViewportView(tblOrder);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Caculator Details:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Total");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Paid");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Return");

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtPaid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPaid.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPaidCaretUpdate(evt);
            }
        });
        txtPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaidActionPerformed(evt);
            }
        });

        txtReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ID.setText("ID");

        txtCusId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCusId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusIdActionPerformed(evt);
            }
        });

        txtBill.setEditable(false);
        txtBill.setColumns(20);
        txtBill.setRows(5);
        jScrollPane2.setViewportView(txtBill);

        uid.setText("jTextField1");

        btnCusReset.setBackground(new java.awt.Color(255, 255, 255));
        btnCusReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCusReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/available_updates_24px.png"))); // NOI18N
        btnCusReset.setBorder(null);
        btnCusReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusResetActionPerformed(evt);
            }
        });

        btnAddCus.setBackground(new java.awt.Color(255, 255, 255));
        btnAddCus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_24px.png"))); // NOI18N
        btnAddCus.setBorder(null);
        btnAddCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCusActionPerformed(evt);
            }
        });

        btnAddProd.setBackground(new java.awt.Color(255, 255, 255));
        btnAddProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_24px.png"))); // NOI18N
        btnAddProd.setBorder(null);
        btnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdActionPerformed(evt);
            }
        });

        btnProdReset.setBackground(new java.awt.Color(255, 255, 255));
        btnProdReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProdReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/available_updates_24px.png"))); // NOI18N
        btnProdReset.setBorder(null);
        btnProdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdResetActionPerformed(evt);
            }
        });

        btnSave2.setBackground(new java.awt.Color(255, 255, 255));
        btnSave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_new_24px.png"))); // NOI18N
        btnSave2.setToolTipText("Add New Order");
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print_24px.png"))); // NOI18N
        jButton1.setToolTipText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPDF.setBackground(new java.awt.Color(255, 255, 255));
        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf_24px.png"))); // NOI18N
        btnPDF.setToolTipText("Generate PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addGap(546, 546, 546)
                                .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTime)
                                    .addComponent(lblDate))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel8)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel7)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(txtCusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel13))
                                                    .addGap(34, 34, 34)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtProdId, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                        .addComponent(txtProdPrice))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel14))
                                                    .addGap(27, 27, 27)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtProdName, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                        .addComponent(txtProdQty))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtCusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(ID)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtCusId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnAddCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCusReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnProdReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 129, Short.MAX_VALUE)
                                        .addComponent(jLabel15)
                                        .addGap(102, 102, 102))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel17))
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                                    .addComponent(txtPaid, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblDate))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblTime)
                            .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txtCusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ID))
                            .addComponent(btnCusReset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtCusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(txtCusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddCus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnProdReset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(txtProdQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtProdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(btnPDF)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave2)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCusIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusIdActionPerformed
        // TODO add your handling code here:
        String cid = txtCusId.getText().trim();

        try {
            Connection conn = new ConnectDB().getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from customers where customer_id like '" + cid + "'");

            if (rs.next()) {
                txtCusId.setText(rs.getString(1));
                txtCusName.setText(rs.getString(2));
                txtCusPhone.setText(rs.getString(3));
                txtCusAddress.setText(rs.getString(4));
            } else {
                txtCusName.setText("");
                txtCusPhone.setText("");
                txtCusAddress.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtCusIdActionPerformed

    public void getUserid(UserAccount userAccount) {
        uid.setText(userAccount.getUser_id());
    }

    private void txtPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaidActionPerformed
        // TODO add your handling code here:
        int paid = Integer.parseInt(txtPaid.getText());
        int total = Integer.parseInt(txtTotal.getText());
        if (total <= paid) {
            ftotal = paid - total;
            String ftotal = String.valueOf(this.ftotal);
            txtReturn.setText(ftotal);
            txtReturn.setEnabled(false);
            txtPaid.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Must be equal or greater than Total!");
        }
    }//GEN-LAST:event_txtPaidActionPerformed

    private void txtProdPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdPriceActionPerformed

    private void txtProdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdIdActionPerformed
        // TODO add your handling code here:
        String pid = txtProdId.getText().trim();

        try {
            Connection conn = new ConnectDB().getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from product where product_id like '" + pid + "'");

            if (rs.next()) {
                txtProdId.setText(rs.getString(1));
                txtProdName.setText(rs.getString(2));
                txtProdPrice.setText(rs.getString(6));
            } else {
                JOptionPane.showMessageDialog(null, "Product does not Exist");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtProdIdActionPerformed

    private void txtCusPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusPhoneActionPerformed
        // TODO add your handling code here:
        String cphone = txtCusPhone.getText().trim();

        try {
            Connection conn = new ConnectDB().getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from customers where phone like '" + cphone + "'");

            if (rs.next()) {
                txtCusId.setText(rs.getString(1));
                txtCusName.setText(rs.getString(2));
                txtCusAddress.setText(rs.getString(4));
            } else {
                txtCusName.setText("");
                txtCusAddress.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtCusPhoneActionPerformed

    private void txtCusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusNameActionPerformed
        // TODO add your handling code here:
        String cname = txtCusName.getText().trim();

        try {
            Connection conn = new ConnectDB().getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from customers where customer_name like '" + cname + "'");

            if (rs.next()) {
                txtCusId.setText(rs.getString(1));
                txtCusName.setText(rs.getString(2));
                txtCusPhone.setText(rs.getString(3));
                txtCusAddress.setText(rs.getString(4));
            } else {
                txtCusId.setText("");
                txtCusPhone.setText("");
                txtCusAddress.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Name does not Exist");
        }
    }//GEN-LAST:event_txtCusNameActionPerformed

    private void btnCusResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusResetActionPerformed
        // TODO add your handling code here:
        txtCusId.setText("");
        txtCusName.setText("");
        txtCusPhone.setText("");
        txtCusAddress.setText("");
    }//GEN-LAST:event_btnCusResetActionPerformed

    private void btnAddCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCusActionPerformed
        // TODO add your handling code here:

        String id = txtCusId.getText().trim();
        String name = txtCusName.getText().trim();
        String phone = txtCusPhone.getText().trim();
        String address = txtCusAddress.getText().trim();

        if (id.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Customer ID and Name");
        } else {
            try {
                Connection conn = new ConnectDB().getConnection();
                PreparedStatement st = null;

                String sql = "insert into customers(customer_id, customer_name, phone, customer_address)"
                        + "value(?, ?, ?, ?)";
                st = conn.prepareStatement(sql);

                st.setString(1, id);
                st.setString(2, name);
                st.setString(3, phone);
                st.setString(4, address);

                st.execute();

                JOptionPane.showMessageDialog(null, "Successfully");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ID is already Exist");
            }
        }
    }//GEN-LAST:event_btnAddCusActionPerformed

    private void btnAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdActionPerformed
        // TODO add your handling code here:
        if (txtProdQty.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter product quantity");
        } else {
            int price = Integer.parseInt(txtProdPrice.getText());
            int qty = Integer.parseInt(txtProdQty.getText());
            int total = price * qty;
            DefaultTableModel tableModel = (DefaultTableModel) tblOrder.getModel();
            tableModel.addRow(new Object[]{txtProdId.getText(), txtProdName.getText(), price, qty, total});
            ftotal = ftotal + total;
            String ftotal = String.valueOf(this.ftotal);
            txtTotal.setText(ftotal);

            txtProdId.setText("");
            txtProdName.setText("");
            txtProdPrice.setText("");
            txtProdQty.setText("");
        }

    }//GEN-LAST:event_btnAddProdActionPerformed

    private void btnProdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdResetActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:

        String total = txtTotal.getText();
        String paid = txtPaid.getText();
        String bal = txtReturn.getText();

        DefaultTableModel tableModel = (DefaultTableModel) tblOrder.getModel();

        txtBill.setText(txtBill.getText() + "------------------------------\n");
        txtBill.setText(txtBill.getText() + "     ADCBE Computer Store\n");
        txtBill.setText(txtBill.getText() + "------------------------------\n");

        txtBill.setText(txtBill.getText() + "Prod\t" + "Price\t" + "SubTotal\n\n");

        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String pname = (String) tableModel.getValueAt(i, 0).toString();
            String price = (String) tableModel.getValueAt(i, 2).toString();
            String subtol = (String) tableModel.getValueAt(i, 4).toString();

            txtBill.setText(txtBill.getText() + pname + "\t" + price + "\t" + subtol + "\n");

        }

        txtBill.setText(txtBill.getText() + "------------------------------\n\n");

        txtBill.setText(txtBill.getText() + "Total: " + total + "\n");
        txtBill.setText(txtBill.getText() + "Paid: " + paid + "\n");
        txtBill.setText(txtBill.getText() + "Return: " + bal + "\n\n");
        txtBill.setText(txtBill.getText() + "------------------------------\n");
        txtBill.setText(txtBill.getText() + "     THANK YOU! COME AGAIN\n");

    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
        // TODO add your handling code here:
        String total = txtTotal.getText();
        String paid = txtPaid.getText();
        String bal = txtReturn.getText();

        if(txtCusId.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter customer");
        }
        
        if (bal.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the payment amount");
        } else {
            DefaultTableModel tableModel = (DefaultTableModel) tblOrder.getModel();

            txtBill.setText(txtBill.getText() + "------------------------------\n");
            txtBill.setText(txtBill.getText() + "     ADCBE Computer Store\n");
            txtBill.setText(txtBill.getText() + "------------------------------\n");

            txtBill.setText(txtBill.getText() + "Prod\t" + "Price\t" + "SubTotal\n\n");

            for (int i = 0; i < tableModel.getRowCount(); i++) {
                String pname = (String) tableModel.getValueAt(i, 0).toString();
                String price = (String) tableModel.getValueAt(i, 2).toString();
                String subtol = (String) tableModel.getValueAt(i, 4).toString();

                txtBill.setText(txtBill.getText() + pname + "\t" + price + "\t" + subtol + "\n");

            }

            txtBill.setText(txtBill.getText() + "------------------------------\n\n");

            txtBill.setText(txtBill.getText() + "Total: " + total + "\n");
            txtBill.setText(txtBill.getText() + "Paid: " + paid + "\n");
            txtBill.setText(txtBill.getText() + "Return: " + bal + "\n\n");
            txtBill.setText(txtBill.getText() + "------------------------------\n");
            txtBill.setText(txtBill.getText() + "      THANK YOU! COME AGAIN\n");

            String date = lblDate.getText();
            String cid = txtCusId.getText();
            String userid = uid.getText();
            int billid = new Random().nextInt(1000000);
           
            
            
            try {
                Connection conn = new ConnectDB().getConnection();
                PreparedStatement st = null;

                String sql = "insert into bills(bill_date, user_id, customer_id, total_amount, bill_id)"
                        + "value(?,?, ?, ?, ?)";
                st = conn.prepareStatement(sql);

                st.setString(1, date);
                st.setString(2, userid);
                st.setString(3, cid);
                st.setString(4, total); 
                st.setInt(5, billid);
                st.execute();

                JOptionPane.showMessageDialog(null, "Successfully");
                //            setVisible(false);
                //            new Customer().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnSave2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
//            txtBill.print(JTable.PrintMode.NORMAL);
            txtBill.print();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
        String name = txtCusName.getText();
        String phone = txtCusPhone.getText();
        String address = txtCusAddress.getText();
        String path = "D:\\File\\NetBeansProjects\\";
        Document doc = new Document();

        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + name + ".pdf"));
            doc.open();

            Paragraph paragraph1 = new Paragraph("                                                            ABCDE Computer Store\n                                                  Contact Number: (+84) 123456789\n\n");
            doc.add(paragraph1);

            Paragraph paragraph2 = new Paragraph("Date & Time: " + lblDate.getText() + " " + lblTime.getText() + "\nCustomer:\nName: " + name + "\nContact No: " + phone + "\nAddress: " + address + "\n\n");
            doc.add(paragraph2);

            PdfPTable tbl = new PdfPTable(5);
            tbl.addCell("ID");
            tbl.addCell("Name");
            tbl.addCell("Price");
            tbl.addCell("Qty");
            tbl.addCell("Sub Total");

            for (int i = 0; i < tblOrder.getRowCount(); i++) {
                String id = tblOrder.getValueAt(i, 0).toString();
                String n = tblOrder.getValueAt(i, 1).toString();
                String p = tblOrder.getValueAt(i, 2).toString();
                String q = tblOrder.getValueAt(i, 3).toString();
                String s = tblOrder.getValueAt(i, 4).toString();
                tbl.addCell(id);
                tbl.addCell(n);
                tbl.addCell(p);
                tbl.addCell(q);
                tbl.addCell(s);
            }

            doc.add(tbl);
            Paragraph paragraph3 = new Paragraph("\nTotal: " + txtTotal.getText() + "\nPaid: " + txtPaid.getText() + "\nReturn: " + txtReturn.getText() + "\n\nTHANK YOU! Please Come Again\nABCDE ComputerStore");
            doc.add(paragraph3);
            doc.close();
            JOptionPane.showMessageDialog(null, "Bill Generated");
            //            setVisible(false);
            //            new Order().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void txtPaidCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPaidCaretUpdate
             // TODO add your handling code here:
    }//GEN-LAST:event_txtPaidCaretUpdate

    private void txtProdQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdQtyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton btnAddCus;
    private javax.swing.JButton btnAddProd;
    private javax.swing.JButton btnCusReset;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnProdReset;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSave2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtCusAddress;
    private javax.swing.JTextField txtCusId;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtCusPhone;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtProdId;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProdPrice;
    private javax.swing.JTextField txtProdQty;
    private javax.swing.JTextField txtReturn;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
